from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('register/', views.register, name="register"),
    path('login/', views.loginPage, name="login"),
    path('search/', views.search, name="search"),
    path('logout/', views.logoutPage, name="logout"),
    path('cart/', views.cart, name="cart"),
    path('checkout/', views.checkout, name="checkout"),
    path('update_item/', views.updateItem, name="update_item"),
    path('introduction/', views.introduction, name="introduction"),
    path('contact/', views.contact, name="contact"),
    path('dell/', views.dell, name="dell"),
    path('acer/', views.acer, name="acer"),
    path('hp/', views.hp, name="hp"),
    path('asus/', views.asus, name="asus"),
    path('lenovo/', views.lenovo, name="lenovo"),
    path('dellinspiron/', views.dellinspiron, name="dellinspiron"),
    path('dellXPS13/', views.dellXPS13, name="dellXPS13"),
    path('dellalienware/', views.dellalienware, name="dellalienware"),
    path('AcerAspire/', views.AcerAspire, name="AcerAspire"),
    path('AcerPredator/', views.AcerPredator, name="AcerPredator"),
    path('Acerswift3/', views.Acerswift3, name="Acerswift3"),
    path('Acerspin3/', views.Acerspin3, name="Acerspin3"),
    path('Acernitro/', views.Acernitro, name="Acernitro"),
    path('Hpspectre/', views.Hpspectre, name="Hpspectre"),
    path('Hpenvy/', views.Hpenvy, name="Hpenvy"),
    path('Hppavilion/', views.Hppavilion, name="Hppavilion"),
    path('Hpelitebook/', views.Hpelitebook, name="Hpelitebook"),
    path('Hpomen/', views.Hpomen, name="Hpomen"),
    path('Hpstream/', views.Hpstream, name="Hpstream"),
    path('Asuszenbook/', views.Asuszenbook, name="Asuszenbook"),
    path('Asusvivobook/', views.Asusvivobook, name="Asusvivobook"),
    path('AsusROG/', views.AsusROG, name="AsusROG"),
    path('AsusTUF/', views.AsusTUF, name="AsusTUF"),
    path('AsusChrome/', views.AsusChrome, name="AsusChrome"),
    path('AsusProart/', views.AsusProart, name="AsusProart"),
    path('LenovoThink/', views.LenovoThink, name="LenovoThink"),
    path('LenovoIdea/', views.LenovoIdea, name="LenovoIdea"),
    path('LenovoYoga/', views.LenovoYoga, name="LenovoYoga"),
    path('LenovoLegion/', views.LenovoLegion, name="LenovoLegion"),
    path('LenovoChrome/', views.LenovoChrome, name="LenovoChrome"),
    path('LenovoX1/', views.LenovoX1, name="LenovoX1"),
]